### ISSUE TITLE
mfd cursor

### ISSUE THREAD

**Issue by bkosaruejr** [cywang90/msfs2020-G3000-enhanced#1]
when using scratch pad to move cursor around it no longer moves with the corresponding movement of the mouse on the pad.  sometime moves only down and to the left no matter which direction you try going

**Comment by cywang90** [comment]
Filed as bug. Will be fixed with the WorkingTitle merge.

**Comment by bkosaruejr** [comment]
Thank you, great work!

**Comment by cywang90** [comment]
Fixed with v0.2.0 pre-release 1 through the WorkingTitle group.
