### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by guifarias31** [cywang90/msfs2020-G3000-enhanced#2]
Hi! Two things I really miss in the G3000'sare the hPa baro option and the ability to turn off Syntetic Vision. Could you try adding this?
Also, there are some conflict files with StuTozer' [G3000-Touchscreens-Restyled mod](https://github.com/StuTozer/G3000-Touchscreens-Restyled). Maybe merging them would be a nice option.

**Comment by cywang90** [comment]
> Hi! Two things I really miss in the G3000'sare the hPa baro option and the ability to turn off Syntetic Vision. Could you try adding this?

I'm in the process of merging with WorkingTitle. I've already sent a pull request and if/when that goes through these features will be in the next release.


> Also, there are some conflict files with StuTozer' [G3000-Touchscreens-Restyled mod](https://github.com/StuTozer/G3000-Touchscreens-Restyled). Maybe merging them would be a nice option.

I've been in touch with the author and they've given me permission to integrate it. Now it's just a matter of when I can get around to it.

**Comment by harii15** [comment]
Hello CYWANG 90 ,
 Loved the TBM G3000 mod.  I Use it regularly!
In the next update , can you please think about adding the status of the landing gear  to the MFD screen . Whether its "UP" or "Down""
 best Regards
 Hari

**Comment by cywang90** [comment]
> In the next update , can you please think about adding the status of the landing gear to the MFD screen . Whether its "UP" or "Down""

Is this a thing in the G3000? I can't find anything in the manual.

**Comment by Andydigital** [comment]
No its not. The huge flashing gear handle and three greens tells you if the gear is up, down or not locked.

**Comment by harii15** [comment]
That’s my point.  In  order to find the status of the landing gear on TO or landing  , one has to actually look below the PFD to see the three green lights next to the landing gear handle 
Wouldn’t it be nice if  one could see it on the MFD screen , next to  ( or below) the flap setting display. 
Hsri

**Comment by Andydigital** [comment]
The point of the mod is to make it the same functionality wise as the real Garmin, not to add quality of life features.

**Comment by harii15** [comment]
My apologies for requesting something that is not in the original Sorry!!
Best 
Hari

**Comment by cywang90** [comment]
altimeter baro units and SVT toggle added with v0.2.0 prerelease 1 through the WorkingTitle group. Please direct any further input to the WorkingTitle github page (see README for link).
